### ISSUE TITLE
Create reference implementation that serves mock data

### ISSUE THREAD

**Issue by brylie** [maas-alliance/apis#12]
Now that we have initial API definitions, we can make a mock service conforming to the designs. This will help developers to adopt the design. To this end, we can create a contract-first (a.k.a. design-first) reference implementation.

# Task
- [ ] choose contract-first development framework
- [ ] scaffold initial app
- [ ] write handler functions to return valid data, conforming to the definition

# Resources
- [Lepo](https://github.com/akx/lepo) - Contract-first REST APIs in Django

**Comment by evermassen** [comment]
I would like to help you out with this task but not 100% familiar with Lepo and Django so it might take a some time. Where do you think we could start with this excercise?

**Comment by evermassen** [comment]
Also a bit struggling with github :-)

**Comment by brylie** [comment]
Ah, hey @evermassen we decided to go with Zalando [Connexion](https://connexion.readthedocs.io/en/latest/) instead of Lepo. Connexion has a [quickstart guide](https://connexion.readthedocs.io/en/latest/quickstart.html).  Try out the basic example, and we can then look specifically at this project API specs.
